name: First Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  list-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: List changed files since last commit
        run: |
          echo "Changed files are:"
          git fetch origin main
          git diff --name-only HEAD^ HEAD
