name: hello-world

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Show System Information
        run: uname -a
      - name: Print Hello World
        run: echo "Hello, world!"
      - name: Show current data
        run: date  
