name: First Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  list-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code (with full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  

      - name: List changed files since last commit
        run: |
          echo "Changed files are:"
          git diff --name-only HEAD^ HEAD || echo "No previous commit to compare."
